###############
# Made by Alemiz
# Show Stats from MiniGames
###############

#Database Connection Settings
#Must be enabled to use RANKS
#Using config SOON...
MySql: false
#MySql Parameters
host: 0.0.0.0
port: 3306
user: root
password: xxxxxx
db: main_db

#Main Messages, Texts
#Use \n to make new line, §c, §a, §b, §l... to make collors
#Interval to show texts in SECONDS
MainInterval: 25
AboutText:
  enable: "true"
  title: "SlivockyStats"
  text: "§aHi everybody!"
  x: 0
  y: 0
  z: 0
  level: "world"
BasicTexts:
  enable: "true"
  title1: "Text1"
  text1: "§aGG!"
  x1: 2
  y1: 2
  z1: 2
  title2: "Text2"
  text2: "§aHaloo!"
  x2: 1
  y2: 1
  z2: 1
  level: "world"

#To enable type "true"
#To disable "false"
#HungerGames
HungerGames:
  enable: "false"
  kills:
    x: 160
    y: 100
    z: 160
  wons:
    x: 180
    y: 100
    z: 180
  level: "world"

#BuildUHC
BuildUHC:
  enable: "false"
  kills:
    x: 160
    y: 100
    z: 160
  wons:
    x: 180
    y: 100
    z: 180
  level: "world"

#SkyWars
SkyWars:
  enable: "false"
  kills:
    x: 160
    y: 100
    z: 160
  wons:
    x: 180
    y: 100
    z: 180
  level: "world"

#Ranks, levels Config - VIP Feature
Ranks:
  Rank1: "Starter"
  Rank2: "Friend"
  Rank3: "Villager"
  Rank4: "Gamer"
  Rank5: "§eEpic"
  Rank6: "§6God"
#Set how mutch $ is XP
#Only if is installed EconomyAPI
Currency: 25